void STDbargraphs(TFile *f, string destination = "stacked_histos"){
    //Returns bar graphs showing the average of the STD of the energy within
    //each window for collisions with total energy 900-1100 GeV for each
    //specified window size. Data are taken from the input file, which should be
    //generated by the function get_sizes.C

    //Setup lists of parameters for constructing histogram names and plotting
    string sizes[7] = {"1x1","4x3","6x5","7x7","9x9","11x10","13x12"};
    int window_no[7] = {0, 2, 4, 5, 6, 8, 10};
    int area_no[11] = {0,1,1,2,2,3,4,5,5,6,6};
    string layers[3] = {"EMCal","IHCal","OHCal"};
    string layer_no[3] = {"0","1","2"};
    string avg_type = "STD";
    short colour[5] = {632,600,616,416,1}; // {kRed, kBlue, kMagenta, kGreen, kBlack} Each centrality range is plotted with a different color/marker on the STD vs window area graphs.
    //short fit_colour[5] = {3,4,5,7,8}; //There's a mismatch between the indicies of ift colours and marker colours.
    short marker[5] = {20, 21, 22, 23, 34};

    //Compute the area of all the window sizes.
    double area[7];
    double Deta, Dphi;
    for(int i = 0; i < 7; i++){
      int size = 0; string Detastr = ""; string Dphistr = "";
      do{
        Detastr = Form("%s%c",Detastr.c_str(),sizes[i][size]);
        size++;
      } while (sizes[i][size] != 'x');
      size++;
      do{
        Dphistr = Form("%s%c",Dphistr.c_str(),sizes[i][size]);
        size++;
      } while (sizes[i][size] != '\0');
      Deta = stoi(Detastr);
      Dphi = stoi(Dphistr);
      area[i] = Deta*Dphi;
    }

    //Define the centraliy ranges we want to plot
    int Cent_bin_ranges[5][2]; //Histogram bins corresponding to energies in TE_ranges.
    string range_str[5];
    for (int i=0; i<5; i++){
        range_str[i] = to_string(20*i) + "-" + to_string(20*(i+1));
        for (int j=0; j<2; j++){
            Cent_bin_ranges[i][j] = i+1;
        }
    }
    /*double X[2];
    for (int i = 0; i<6; i++){
        X[i] = i+0.5;
    }*/

    //Create the file to write shit to and the canvas to plot shit on
    TFile *k = new TFile("STDbargraphs.root","RECREATE");
    TCanvas *c1 = new TCanvas("c1","c1");
    c1->SetGrid();

    for (int layer=0; layer<4; layer++){ // 4 calo layers: total energy, EMCal, IHCal, and OHCal

        //Setup arrays to contain points and error bars we want to graph. Note that the x-values are contained in areas[11].
        double Xerr[7] = {0};
        double Y[5][7];
        double Yerr[5][7];
        TH1D *proj[7][5];
        string name;


        for (int range=0; range < 5; range++){

            //Do we need this line?
            int area_count[7] = {0,0,0,0,0,0,0};

            for (int window = 0; window < 7; window++){
                //Read in the centrality histogram for the given window size and calorimeter
                if (layer == 0) name = Form("h_%stot%i_Cent", avg_type.c_str(), window_no[window]);
                else name = Form("h_%s%i_layer%i_Cent", avg_type.c_str(), window_no[window], layer-1);
                TH2D *h = (TH2D*) ((TH2D*) f->Get(name.c_str()))->Clone("h");

                //Project histogram, get the mean STD and error, and add the point to
                //the graph.
                if (layer == 0){
                    proj[window][range] = h->ProjectionY( Form("proj%s%s_range%s%s_tot",avg_type.c_str(),sizes[window].c_str(),range_str[range].c_str(),"%") ,Cent_bin_ranges[range][0],Cent_bin_ranges[range][1],"o");
                    proj[window][range]->SetTitle( Form("proj%s%s_range%s%s_tot",avg_type.c_str(),sizes[window].c_str(), range_str[range].c_str(),"%") );
                }
                else {
                    proj[window][range] = h->ProjectionY( Form("proj%s%s_layer%s_range%s%s",avg_type.c_str(),sizes[window].c_str(),layers[layer-1].c_str(), range_str[range].c_str(),"%"),Cent_bin_ranges[range][0],Cent_bin_ranges[range][1],"o");
                    proj[window][range]->SetTitle( Form("proj%s%s_layer%s_range%s%s",avg_type.c_str(),sizes[window].c_str(),layers[layer-1].c_str(), range_str[range].c_str(), "%") );
                }
                proj[window][range]->GetYaxis()->SetTitle("count");
                proj[window][range]->GetXaxis()->SetTitle("STD (GeV)");
                proj[window][range]->GetYaxis()->SetTitleSize(0.045);
                proj[window][range]->GetXaxis()->SetTitleSize(0.045);
                Y[range][window] = proj[window][range]->GetMean(1);
                proj[window][range]->Write();
                proj[window][range]->Draw();
                if (layer == 0) c1->Print(Form("%s/proj%s%s_range%s_tot.pdf",destination.c_str(),avg_type.c_str(),sizes[window].c_str(), range_str[range].c_str()));
                else c1->Print(Form("%s/proj%s%s_layer%s_range%s.pdf",destination.c_str(),avg_type.c_str(),sizes[window].c_str(),layers[layer-1].c_str(), range_str[range].c_str()));
                Yerr[range][window] = proj[window][range]->GetStdDev() / TMath::Sqrt(proj[window][range]->GetEntries());
                /*if (Y[0][area_no[window]] == 0){
                    Y[0][area_no[window]] = mean;
                    Yerr[0][area_no[window]] = err;
                } else if (Y[1][area_no[window]] == 0){
                    Y[1][area_no[window]] = mean;
                    Yerr[1][area_no[window]] = err;
                }else{
                    Y[2][area_no[window]] = mean;
                    Yerr[2][area_no[window]] = err;
                }*/
            }
        }

        // TODO: each calo shall be 1 graph with each centrality range plotted with a different color/marker.
            // Try: 1.) plot each centrality range on its own graph
            // 2.) fit each graph separately
            // 3.) create 1 master legend contaning colors/fit parameters for all graphs
            // 4.) draw all graphs on 1 axes, starting with the highest centrality bin

        //Create the graphs
        TLegend *l = new TLegend(0.1,0.69,0.3,0.9);
        TGraphErrors *gr1[5];
        for (int range=0; range<5; range++){
            gr1[range] = new TGraphErrors(7,area,Y[range],Xerr,Yerr[range]);
            gr1[range]->SetMarkerStyle(marker[range]);
            gr1[range]->SetMarkerSize(1.4);
            gr1[range]->SetMarkerColor(colour[range]);
            gr1[range]->SetLineColor(colour[range]);
            if (range == 0){
                //Set graph title only for the highest centrality range
                if (layer == 0) gr1[range]->SetTitle("Mean STD of Et in Entire Detector wrt Window Size");
                else gr1[range]->SetTitle( Form("Mean STD of Et in %s wrt Window Size", layers[layer-1].c_str()) );
            }
            gr1[range]->GetYaxis()->SetTitle("Avg STD (GeV)");
            gr1[range]->GetXaxis()->SetTitle("Window area (towers)");
            gr1[range]->SetMinimum(0);

            //Fit each graph and record fitting parameters
            /*TF1 *f1 = new TF1("f1","[0]*TMath::Power(x,[1])");
            f1->SetParameters(0.3,0.4);
            TStyle *st1 = new TStyle("st1","my style");
            st1->SetFuncColor(fit_colour[range]);
            st1->cd();
            TFitResultPtr r = gr1[range]->Fit(f1, "S", "", 1, 156);
            double sigma_1x1 = r->Parameter(0);
            double sigma_err = r->ParError(0);
            double power = r->Parameter(1);
            double powererr = r->ParError(1);*/

            l->AddEntry(gr1[range], Form("%s%s",range_str[range].c_str(), "%") );

            // Draw the graphs
            // Draw the highest-centrality graph first, with axes
            if (range == 0) gr1[range]->Draw("AP");
            // Draw the rest of the graphs on the same axes
            else gr1[range]->Draw("P");
        }

        /*Double_t *x = gr1->GetX();
        Double_t *y = gr1->GetY();
        for (int i : ROOT::TSeqI(11)){
            if (area_count[area_no[i]] == 0){
                TMarker *m = new TMarker(x[i], y[i], 21); //squares
                area_count[area_no[i]]++;
                m->SetMarkerColor(6);
                m->SetMarkerSize(1.3);
                m->Draw();
            } else if (area_count[area_no[i]] == 1){
                area_count[area_no[i]]++;
                TMarker *m = new TMarker(x[i], y[i], 20); //circles
                m->SetMarkerColor(8);
                m->SetMarkerSize(1.3);
                m->Draw();
            }
        } */

        //Draw the legend
        l->Draw();
        //If the window strings of equal area are given in the order of wider-phi
        //windows first, then the same order will be preserved here. Then, 
        //circular markers will mark windows which are wider in eta than phi.
                
        /*TGraphErrors *gr2 = new TGraphErrors(2,X,Y[1],Xerr,Yerr[1]);
        TGraphErrors *gr3 = new TGraphErrors(6,X,Y[2],Xerr,Yerr[2]);
        for (int i=0; i<6; i++){
            if (i != 3){
                X[i]=0; Y[0][i]=0; Yerr[0][i]=0;
            }
        }
        TGraphErrors *gr4 = new TGraphErrors(6,X,Y[0],Xerr,Yerr[0]);
        gr1->SetFillColor(kGreen);
        gr2->SetFillColor(kBlue);
        //gr3->SetFillColor(kRed);
        //gr4->SetFillColor(kGreen);
        gr1->Draw("AB");
        //gr3->Draw("B");
        gr2->Draw("B");
        //gr4->Draw("B"); */

        // Print and write the canvas
        if (layer==0) c1->Print(Form("%s/STDtotals.pdf",destination.c_str()));
        else c1->Print( Form("%s/STD_layer%s.pdf",destination.c_str(), layers[layer-1].c_str()) );

        c1->Write();
    }

    k->Close();
    c1->Close();

}
